### ISSUE TITLE
Device support + Error message

### ISSUE THREAD

**Issue by Fannangir** [milo526/homebridge-tuya-web#18]
Hi,
After moving from vitramir to this one (milo), I receive the following messages:
1. [TuyaWebPlatform] Could not init class for device type [cover]
My cover device does not work

2. [TuyaWebPlatform] Error retrieving devices states TypeError: Cannot read property 'updateAccessory' of undefined
    at /usr/lib/node_modules/@milo526/homebridge-tuya-web/index.js:96:52
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
 
Thanks,
Arie.

**Comment by mbierman** [comment]
@Fannangir it might help if you said which library you moved from where presumably it was working?

**Comment by Fannangir** [comment]
Sorry it was not clear enough, I have moved from Tuya Web fork by vitramir:
https://www.npmjs.com/package/@vitramir/homebridge-tuya-web

**Comment by Faisalthe01** [comment]
Yes It won’t as there is not accessory for Cover in this one.

**Comment by milo526** [comment]
Hello,

Indeed the cover accessory is not (yet) supported. 

A fix for the second problem is currently in pre-release and can be installed by using `npm I @milo525/homebridge-tuya-web@next`.

**Comment by Fannangir** [comment]
Is there a target date for cover accessory? :)

**Comment by milo526** [comment]
Not an exact date but it should not be more than a few days after somebody [makes a pull request](https://github.com/milo526/homebridge-tuya-web/compare) or [sponsors me](https://github.com/sponsors/milo526) so I can buy a Tuya cover accessory and create it myself 😄.

Where you able to test if the `@next` release works for you? So far as that it doesn't crash.

**Comment by Fannangir** [comment]
As I have mentioned earlier, I have homebridge-tuya-web by @vitramir revision 0.1.2.
It contains the cover accessory support working well.
The contents of this accessory type js file is below.
Maybe you could integrate it into your plugin?
Thanks.

"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg,
_arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new
P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value));
} catch (e) { reject(e); } }
        function rejected(value) { try {
step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) :
adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if
(Object.hasOwnProperty.call(mod, k)) result[k] = mod[k];
    result["default"] = mod;
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
const hap_nodejs_1 = require("hap-nodejs");
const base_accessory_1 = require("./base_accessory");
const promisifyEvent_1 = require("./promisifyEvent");
const R = __importStar(require("ramda"));
const transformations_1 = require("./transformations");
const defaultConfig = {
    useCache: true,
    toTuyaBrightness: [],
    fromTuyaBrightness: [
        {
            type: transformations_1.TransformationType.parseInt,
        },
        {
            type: transformations_1.TransformationType.divide,
            value: 255,
        },
        {
            type: transformations_1.TransformationType.multiply,
            value: 100,
        },
        {
            type: transformations_1.TransformationType.floor,
        },
    ],
};
var DeviceState;
(function (DeviceState) {
    DeviceState[DeviceState["opening"] = 1] = "opening";
    DeviceState[DeviceState["closing"] = 2] = "closing";
    DeviceState[DeviceState["stopped"] = 3] = "stopped";
    DeviceState[DeviceState["open"] = 4] = "open";
    DeviceState[DeviceState["closed"] = 5] = "closed";
})(DeviceState || (DeviceState = {}));
class WindowCoveringAccessory extends base_accessory_1.BaseAccessory {
    constructor(platform, homebridgeAccessory, deviceConfig, config) {
        super(platform, homebridgeAccessory, deviceConfig,
hap_nodejs_1.Accessory.Categories.WINDOW_COVERING);
        this.config = R.merge(defaultConfig, config);
        this.service
            .getCharacteristic(hap_nodejs_1.Characteristic.TargetPosition)
            .on(hap_nodejs_1.CharacteristicEventTypes.GET,
promisifyEvent_1.pifyGetEvt(() => __awaiter(this, void 0, void 0,
function* () {
            let state = yield this.getState();
            if (state === DeviceState.opening || state === DeviceState.open) {
                return 100;
            }
            else if (state === DeviceState.closing ||
                state === DeviceState.closed) {
                return 0;
            }
            else if (state === DeviceState.stopped) {
                return 50;
            }
        })))
            .on(hap_nodejs_1.CharacteristicEventTypes.SET,
promisifyEvent_1.pifySetEvt((percentage) => __awaiter(this, void 0,
void 0, function* () {
            try {
                if (percentage === 50) {
                    this.updateCache(DeviceState.stopped);
                    yield
this.platform.tuyaWebApi.setDeviceState(this.deviceId, 'startStop', {
value: 0 });
                }
                else if (percentage === 100) {
                    this.updateCache(DeviceState.opening);
                    yield
this.platform.tuyaWebApi.setDeviceState(this.deviceId, 'turnOnOff', {
value: 1 });
                }
                else if (percentage === 0) {
                    this.updateCache(DeviceState.closing);
                    yield
this.platform.tuyaWebApi.setDeviceState(this.deviceId, 'turnOnOff', {
value: 0 });
                }
            }
            catch (err) {
                console.log(err);
            }
        }))).props.minStep = 50;
        this.service.getCharacteristic(hap_nodejs_1.Characteristic.PositionState).on(hap_nodejs_1.CharacteristicEventTypes.GET,
promisifyEvent_1.pifyGetEvt(() => __awaiter(this, void 0, void 0,
function* () {
            let state = yield this.getState();
            if (state === DeviceState.opening) {
                return hap_nodejs_1.Characteristic.PositionState.INCREASING;
            }
            else if (state === DeviceState.closing) {
                return hap_nodejs_1.Characteristic.PositionState.DECREASING;
            }
            else if (state === DeviceState.closed ||
                state === DeviceState.open ||
                state === DeviceState.closed) {
                return hap_nodejs_1.Characteristic.PositionState.STOPPED;
            }
        })));
        this.service.getCharacteristic(hap_nodejs_1.Characteristic.CurrentPosition).on(hap_nodejs_1.CharacteristicEventTypes.GET,
promisifyEvent_1.pifyGetEvt(() => __awaiter(this, void 0, void 0,
function* () {
            let state = yield this.getState();
            if (state === DeviceState.opening || state === DeviceState.open) {
                return 100;
            }
            else if (state === DeviceState.closing ||
                state === DeviceState.closed) {
                return 0;
            }
            else if (state === DeviceState.stopped) {
                return 50;
            }
        })));
    }
    updateCache(state) {
        let prevState = DeviceState.stopped;
        if (this.hasValidCache()) {
            prevState =
this.getCachedState(hap_nodejs_1.Characteristic.PositionState);
        }
        let newState = state;
        if (state === DeviceState.stopped &&
            (prevState === DeviceState.opening || prevState ===
DeviceState.open)) {
            newState = DeviceState.open;
        }
        else if (state === DeviceState.stopped &&
            (prevState === DeviceState.closing || prevState ===
DeviceState.closed)) {
            newState = DeviceState.closed;
        }
        this.setCachedState(hap_nodejs_1.Characteristic.PositionState,
newState);
    }
    getState() {
        return __awaiter(this, void 0, void 0, function* () {
            let state;
            if (this.config.useCache && this.hasValidCache()) {
                state =
this.getCachedState(hap_nodejs_1.Characteristic.PositionState);
            }
            else {
                const data = yield
this.platform.tuyaWebApi.getDeviceState(this.deviceId);
                state = data.state;
            }
            return state;
        });
    }
    updateState(data) {
        return __awaiter(this, void 0, void 0, function* () {
            // Update device type specific state
            this.log.debug('[UPDATING][%s]:',
this.homebridgeAccessory.displayName, data);
            this.updateCache(Number(data.state));
            this.service
                .getCharacteristic(hap_nodejs_1.Characteristic.PositionState)

.updateValue(this.getCachedState(hap_nodejs_1.Characteristic.PositionState));
        });
    }
}
exports.WindowCoveringAccessory = WindowCoveringAccessory;

**Comment by milo526** [comment]
Hey, thank for your trying to help; What you posted is compiled TypeScript, sadly this is completely unmaintainable and in its current form cannot be used in the library. Furthermore if we look at [the typescript version of this file](https://github.com/vitramir/homebridge-tuya-web/blob/feature/window-covering/src/window_covering.ts) we can see that it uses some functionality such as the transformations what "my" library also does not support currently.

Sneak-peek, I'm currently working on a typescript re-write of this library, once that it done it will help speed up creation of new accessories tremendously, you'll have to wait +/- 1 month for that (first have to take some exams 😉)

**Comment by Fannangir** [comment]
Understood. Thought it might help, or at least provide any clue.
Good luck :).

**Comment by milo526** [comment]
Just receive this data from somebody using the covers, if you yourself have some Tuya cover devices and want support please also drop your device config here!

```
{
   "header":{
      "code":"SUCCESS",
      "payloadVersion":1
   },
   "payload":{
      "devices":[
         {
            "data":{
               "online":True,
               "state":3,
               "support_stop":True
            },
            "dev_type":"cover",
            "ha_type":"cover",
            "icon":"https://images.tuyaeu.com/smart/product_icon/cl.png",
            "id":"42787240807d3a010626",
            "name":"Curtain2"
         },
         {
            "data":{
               "online":True,
               "state":3,
               "support_stop":True
            },
            "dev_type":"cover",
            "ha_type":"cover",
            "icon":"https://images.tuyaeu.com/smart/product_icon/cl.png",
            "id":"427872402462ab0a7685",
            "name":"Name0"
         },
         {
            "data":{
               "online":True,
               "state":3,
               "support_stop":True
            },
            "dev_type":"cover",
            "ha_type":"cover",
            "icon":"https://images.tuyaeu.com/smart/product_icon/cl.png",
            "id":"42787240807d3a01048c",
            "name":"Name1"
         },
         {
            "data":{
               "online":True,
               "state":3,
               "support_stop":True
            },
            "dev_type":"cover",
            "ha_type":"cover",
            "icon":"https://images.tuyaeu.com/smart/product_icon/cl.png",
            "id":"427872402462ab0aac7e",
            "name":"Name2"
         },
         {
            "data":{
               "online":True,
               "state":3,
               "support_stop":True
            },
            "dev_type":"cover",
            "ha_type":"cover",
            "icon":"https://images.tuyaeu.com/smart/product_icon/cl.png",
            "id":"42787240a4cf12d3be9b",
            "name":"Name3"
         }
      ],
      "scenes":[

      ]
   }
}```

**Comment by Aekung** [comment]
Hi,

I posted in another thread but I am posting it here once again for the device config. Hopefully it would help.

```
{
   "header":{
      "code":"SUCCESS",
      "payloadVersion":1
   },
   "payload":{
      "devices":[
         {
            "data":{
               "online":True,
               "state":3,
               "support_stop":True
            },
            "dev_type":"cover",
            "ha_type":"cover",
            "icon":"https://images.tuyaus.com/smart/product_icon/cl.png",
            "id":"52003233ecfabca9fdce",
            "name":"Window Cover for Front Door"
         },
         {
            "data":{
               "online":True,
               "state":True
            },
            "dev_type":"switch",
            "ha_type":"switch",
            "icon":"https://images.tuyaus.com/smart/program_category_icon/kg.png",
            "id":"138766762cf432caa04b",
            "name":"Bedroom Light"
         },
         {
            "data":{
               "online":True,
               "state":3,
               "support_stop":True
            },
            "dev_type":"cover",
            "ha_type":"cover",
            "icon":"https://images.tuyaus.com/smart/product_icon/cl.png",
            "id":"10670875bcddc2b0e398",
            "name":"Window Cover for Garden"
         },
         {
            "data":{
               "online":True,
               "state":2,
               "support_stop":True
            },
            "dev_type":"cover",
            "ha_type":"cover",
            "icon":"https://images.tuyaus.com/smart/program_category_icon/cl.png",
            "id":"630777045002914b3123",
            "name":"Window Cover for Home Theater"
         }
      ],
      "scenes":[

      ]
   }
```

Let me know if I missed something or you want me to do something more.

**Comment by NamelessPharaoh** [comment]
Any updates?

**Comment by milo526** [comment]
My house still does not have any Tuya cover devices, this makes it hard for me to develop for this accessory. Therefor the first part of [this comment](https://github.com/milo526/homebridge-tuya-web/issues/18#issuecomment-649708325) still applies 😉.

I hope you understand that the motivation to make something is severely reduced if the creator cannot enjoy the fruits of their labour. Not to say that I will never add support for this device but with the current setup it will take quite some time and I will require a lot of help from people who do have a cover accessory.

**Comment by Fannangir** [comment]
Hi Milo,
A few points:
1. I have moved to a custom tuya implementation under Home Assistant, I control only RGB lights at the moment as I had no time to flash its firmware yet.
2. As for Covers, I have flashed firmware to HAA, works perfect including reporting current covers state (position) and end points (it just took me a while to figure out the config file).
3. I have updated your plugin o the latest version. I can see that it provides no feedback of current switch state if it is switched via smart_life app or Home Assistant, and the log keeps showing the following ("Requesting too quickly"):
![image](https://user-images.githubusercontent.com/30548574/90005718-45ac0180-dca0-11ea-99c8-c4d2a20b9a7f.png)

Generally speaking, if there is no real request for Cover by others, you can close the request.
Thank you very much for the effort.

**Comment by milo526** [comment]
Thanks for your feedback; I believe there are others that still want this so I'll leave it open for now.

With regards to your third issue please see [this](https://github.com/milo526/homebridge-tuya-web/issues/50#issuecomment-672724211).

**Comment by Pelagious** [comment]
I have a cover device that I would be interested in testing for. I would really like to see cover support added. My config is below, (at the moment I'm overriding the default to make it behave as a switch, which is irritating because it is  stateless switch and I can't make it stateful)

```

{
    "bridge": {
        "name": "Homebridge XXXX",
        "username": "xxxxxxx",
        "port": xxxxxx,
        "pin": "xxx-xx-xxx"
    },
    "accessories": [
        {
            "accessory": "SwitchBot",
            "name": "Basement Fan",
            "macAddress": "xxxxxxxxxx",
            "stateLess": false
        },
        {
            "name": "Dummy switch 1",
            "stateful": true,
            "reverse": false,
            "time": 1000,
            "accessory": "DummySwitch"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8085,
            "auth": "form",
            "theme": "dark-mode",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config",
            "sudo": true,
            "log": {
                "method": "native",
                "path": "/var/lib/homebridge/homebridge.log"
            },
            "sessionTimeout": 28800
        },
        {
            "name": "TuyaWebPlatform",
            "options": {
                "username": "xxxxxxxxxx",
                "password": "xxxxxxxxxxx",
                "countryCode": "1",
                "platform": "tuya"
            },
            "defaults": [
                {
                    "id": "xxxxxxxxxxxxxx",
                    "device_type": "switch"
                }
            ],
            "scenes": true,
            "platform": "TuyaWebPlatform"
        }
    ]
}

```

**Comment by milo526** [comment]
@Pelagious Hello and thank you for your interest in this plugin, could you please enable debugging in homebridge and upload the debug logs?

**Comment by Pelagious** [comment]
Sure, operating off of phone. Let me know if I need to repost this properly from a computer for better formatting 

```
[8/14/2020, 11:43:49] [Config] Homebridge restart request received [8/14/2020, 11:43:50] [Config] No restart command defined, killing process... [8/14/2020, 11:43:50] [HB Supervisor] Stopping services... [8/14/2020, 11:43:50] Got SIGTERM, shutting down Homebridge... [8/14/2020, 11:43:55] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null [8/14/2020, 11:44:02] [HB Supervisor] OS: Linux 5.4.51-v7l+ arm [8/14/2020, 11:44:02] [HB Supervisor] Node.js v12.18.2 /usr/local/bin/node [8/14/2020, 11:44:02] [HB Supervisor] Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge [8/14/2020, 11:44:02] [HB Supervisor] UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js [8/14/2020, 11:44:02] [HB Supervisor] Starting Homebridge with extra flags: -I -D [8/14/2020, 11:44:02] [36m[HB Supervisor] Started Homebridge v1.1.2 with PID: xxxx [8/14/2020, 11:44:03] Loaded config.json with 2 accessories and 2 platforms. [8/14/2020, 11:44:03] --- [8/14/2020, 11:44:04] Loaded plugin: homebridge-config-ui-x@4.25.2 [8/14/2020, 11:44:04] Registering platform 'homebridge-config-ui-x.config' [8/14/2020, 11:44:04] --- [8/14/2020, 11:44:04] Loaded plugin: homebridge-dummy@0.4.1 [8/14/2020, 11:44:04] Registering accessory 'homebridge-dummy.DummySwitch' [8/14/2020, 11:44:04] --- [8/14/2020, 11:44:06] [Config] Homebridge Config UI X v4.25.2 is listening on :: port 8085 [8/14/2020, 11:44:05] Loaded plugin: homebridge-ifttt@0.4.1 [8/14/2020, 11:44:05] Registering platform 'homebridge-ifttt.IFTTT' [8/14/2020, 11:44:05] --- [8/14/2020, 11:44:05] Loaded plugin: homebridge-switchbot-plus@0.2.1 [8/14/2020, 11:44:05] Plugin 'homebridge-switchbot-plus' tried to register with an incorrect plugin identifier: 'homebridge-switchbot'. Please report this to the developer! [8/14/2020, 11:44:05] Registering accessory 'homebridge-switchbot-plus.SwitchBot' [8/14/2020, 11:44:05] --- [8/14/2020, 11:44:05] Loaded plugin: @milo526/homebridge-tuya-web@0.4.3 [8/14/2020, 11:44:05] Registering platform '@milo526/homebridge-tuya-web.TuyaWebPlatform' [8/14/2020, 11:44:05] --- [8/14/2020, 11:44:05] Loading 2 platforms... [8/14/2020, 11:44:05] [Config] Initializing config platform... [8/14/2020, 11:44:05] [Config] Running in Service Mode [8/14/2020, 11:44:05] [TuyaWebPlatform] Initializing TuyaWebPlatform platform... [8/14/2020, 11:44:05] [TuyaWebPlatform] Finished initializing platform: TuyaWebPlatform [8/14/2020, 11:44:05] Loading 2 accessories... [8/14/2020, 11:44:05] [Basement Fan] Initializing SwitchBot accessory... [8/14/2020, 11:44:05] [Dummy switch 1] Initializing DummySwitch accessory... [8/14/2020, 11:44:05] [Dummy switch 1] Setting switch to true [8/14/2020, 11:44:05] [TuyaWebPlatform] Loading accessory from cache: Open the kitchen blinds [8/14/2020, 11:44:05] [TuyaWebPlatform] Loading accessory from cache: Close the kitchen blinds [8/14/2020, 11:44:05] [TuyaWebPlatform] Loading accessory from cache: Kitchen blinds [8/14/2020, 11:44:05] [TuyaWebPlatform] Requesting new token Setup Payload: X-HM://0024IAFNVHE8E Enter this code with your HomeKit app on your iOS device to pair with Homebridge: â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â” â”‚ xxx-xx-xxx â”‚ â””â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”˜ [8/14/2020, 11:44:05] Homebridge is running on port 51202. [8/14/2020, 11:44:06] [TuyaWebPlatform] Sending HTTP GET request to /homeassistant/skill. [8/14/2020, 11:44:07] [TuyaWebPlatform] Device type for "Kitchen blinds " is overruled in config to: "scene" [8/14/2020, 11:44:07] [TuyaWebPlatform] [Kitchen blinds ] deviceConfig: { data: { support_stop: true, online: true, state: 1 }, name: 'Kitchen blinds ', icon: 'https://images.tuyaus.com/smart/program_category_icon/cl.png', id: '20406812807d3a04b6a0', dev_type: 'scene', ha_type: 'cover' } [8/14/2020, 11:44:07] [TuyaWebPlatform] Existing Accessory found [Name: Kitchen blinds ] [Tuya ID: xxxxxxxxxxxxxxxxxxx] [HomeBridge ID: 39d7a6d1-f4e3-4982-8422-6c13acfc1afb] [8/14/2020, 11:44:07] [TuyaWebPlatform] [Kitchen blinds ] Characteristic.MomentaryOn - Enabled [8/14/2020, 11:44:07] [TuyaWebPlatform] [Open the kitchen blinds ] deviceConfig: { data: {}, name: 'Open the kitchen blinds ', id: 'YZrLjxfJfGRP8a0w', dev_type: 'scene', ha_type: 'scene' } [8/14/2020, 11:44:07] [TuyaWebPlatform] Existing Accessory found [Name: Open the kitchen blinds ] [Tuya ID: YZrLjxfJfGRP8a0w] [HomeBridge ID: 208961e4-5dae-4728-a734-5a87014216f1] [8/14/2020, 11:44:07] [TuyaWebPlatform] [Open the kitchen blinds ] Characteristic.MomentaryOn - Enabled [8/14/2020, 11:44:07] [TuyaWebPlatform] [Close the kitchen blinds ] deviceConfig: { data: {}, name: 'Close the kitchen blinds ', id: 'smq7QNNUAva2mPE2', dev_type: 'scene', ha_type: 'scene' } [8/14/2020, 11:44:07] [TuyaWebPlatform] Existing Accessory found [Name: Close the kitchen blinds ] [Tuya ID: smq7QNNUAva2mPE2] [HomeBridge ID: cf40e473-e9a7-4eb4-b823-4dca19d41326] [8/14/2020, 11:44:07] [TuyaWebPlatform] [Close the kitchen blinds ] Characteristic.MomentaryOn - Enabled [8/14/2020, 11:44:15] [TuyaWebPlatform] [Open the kitchen blinds ] Characteristic.MomentaryOn - [GET] 0 [8/14/2020, 11:44:15] [TuyaWebPlatform] [Close the kitchen blinds ] Characteristic.MomentaryOn - [GET] 0 [8/14/2020, 11:44:15] [TuyaWebPlatform] [Kitchen blinds ] Characteristic.MomentaryOn - [GET] 0

```

**Comment by Pelagious** [comment]
Let me know if you need me to do config changes. I'm currently running the blinds as a switch-scene and imported the tuya scenes for opening and closing the blinds, since for whatever reason, when I override the blinds from a cover to a switch it is irritatingly stateless. Which really ruins a lot of automations

**Comment by costispavlou** [comment]
Hi everyone and @milo526. Problem is indeed fixed but only one out of the 3 accessories (boiler switch) is showing.
My two shutters (set previously as covers) are not. Any chance I'm doing anything wrong?
Here's my log:
[TuyaWebPlatform] Existing Accessory found [Name: Boiler Switch] [Tuya ID: ***] [HomeBridge ID: **]
[TuyaWebPlatform] [Boiler Switch] Characteristic.On - Enabled
[TuyaWebPlatform] Could not init class for device type [cover]

and config:

"defaults": [
{
"id": "606020702cf4323eb64b",
"device_type": "Cover"
},
{
"id": "606020702cf4323e73fa",
"device_type": "Cover"
}
],

Is cover not yet supported? I used an other plugin for them before I switched to yours and everything was working and cover was supported.

Edit:
8/18/2020, 7:06:54 PM Skipping plugin found at "/home/hoobs/.hoobs/node_modules/@vitramir/homebridge-tuya-web" since we already loaded the same plugin from "/home/hoobs/.hoobs/node_modules/@milo526/homebridge-tuya-web".

Can someone help me edit my config and set it to work normally again? 
@Pelagious or @Aekung can you advise please? 
I'm using hoobs btw. 
Thanks in advance.

**Comment by milo526** [comment]
@costispavlou please read the readme at the root of this repository, that contains quite some useful information 😜 amongst others it states that covers are indeed not yet supported. There is an issue in this repo requesting cover support.

**Comment by costispavlou** [comment]
Hi @milo526 thank you for the feedback. I did read that you're not yet supporting this, I was just wondering if you found a workaround like vitramir did.

**Comment by costispavlou** [comment]
I'm also trying to remove the previous plugin I used so as to have the functionality at least as switch, but 
sudo rm -Rf /home/hoobs/.hoobs/node_modules/@vitramir/homebridge-tuya-web does not work.

**Comment by milo526** [comment]
Yeah the work around is overwriting them to switches; then you should be able to use them.
Otherwise create tuya scenes and expose those

**Comment by costispavlou** [comment]
I tried 100 times it doesnt work. 
What am I doing wrong? 
I'm pasting this in overwrite
[{"id": "606020702cf4323eb64b",
   "device_type": "Switch"},
{"id": "606020702cf4323e73fa",
"device_type": "Switch"}
]

**Comment by milo526** [comment]
I will probably have some time coming week to look at this.
I need somebody with a cover accessory who can run some tests for me, if you feel like doing so please express that in this issue or even better in the [#tuya-web channel on the homebridge discord](https://discord.gg/5f3K7f).

Some of the questions I am struggling with assuming the following data for example:

```json
{
  "online":true,
  "state":3,
  "support_stop":true
},
```

1) Will we be able to read the status of the covers? i.e. if they are open, opening, closed, closing, how far are they opened? etc.
  I strongly suspect the state parameter in this request has something to do with this.
2) Will we be able to set a status for the covers to only have them open a certain percentage.

To implement this I will at least need to know the current position of the covers (how far openend), their target position (this will need to be set), their "state" (opening, closing, stopped) and I will probably need to implement the hold position property to allow you'll to stop the covers half way through their motion (but what do we report as state then?)

So if you have a cover accessory, want support for it in this library, have some technical know-how (preferably able to run python scripts) and have some time available in the next week please reach out (preferably through discord, otherwise respond to this comment)!
If you are not in the above mentioned group and still would like to see support for the window cover added, please consider [donating](https://github.com/milo526/homebridge-tuya-web) to this library so I can buy a tuya powered window cover and test it locally!

**Comment by costispavlou** [comment]
vitramir/homebridge-tuya-web version which had that support was not having states or anything. 
It was working practically like an Up / Down / Stop-Pause 
Should the cover be open - status was Open
Should the cover be closed - status was closed
Should the cover be stopped at any point while open/close - status was 50% Open

As for question 2, I don't think that would be necessary for any one of us having these type of covers as each cover/shutter etc has a different speed for open / close. Therefore it would need some recalibration and all. However I don't see how this couldn't be done in the sense of: [if cover closed] and command [75% open] then open for 5 seconds, then stop/pause.

**Comment by taaa22** [comment]
Please support cover device

Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {   'online': True,
                                                  'state': 2,
                                                  'support_stop': True},
                                      'dev_type': 'cover',
                                      'ha_type': 'cover',
                                      'icon': 'https://images.tuyaeu.com/smart/program_category_icon/cl.png',
                                      'id': '31381150cc50e3ff0586',
                                      'name': 'Chain Controller'},
                                  {   'data': {'online': True, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/15574115509uyay5yqre7_0.jpg',
                                      'id': '85006400bcddc2679fdf_1',
                                      'name': 'Switch 1'},
                                  {   'data': {'online': True, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/15574115509uyay5yqre7_0.jpg',
                                      'id': '85006400bcddc2679fdf_2',
                                      'name': 'Switch 2'},
                                  {   'data': {'online': True, 'state': True},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/15574115509uyay5yqre7_0.jpg',
                                      'id': '85006400bcddc2679fdf_3',
                                      'name': 'Switch 3'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/15574115509uyay5yqre7_0.jpg',
                                      'id': '85006400bcddc26704a1_1',
                                      'name': 'Switch 1'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/15574115509uyay5yqre7_0.jpg',
                                      'id': '85006400bcddc26704a1_2',
                                      'name': 'Switch 2'},
                                  {   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/15574115509uyay5yqre7_0.jpg',
                                      'id': '85006400bcddc26704a1_3',
                                      'name': 'Switch 3'}],
                   'scenes': []}}

**Comment by Yayaa10** [comment]
Hello, I'm very interested to use tuya cover switch through homebridge.
I have try to use the the this advanced configurations.

This is my configuration for Tuya devices:

        {
            "platform": "TuyaWebPlatform",
            "name": "TuyaWebPlatform",
            "options": {
                "username": "XXXXXXXXXXXXXXXXXXX",
                "password": "XXXXXXXXXXXXXXXXXXX",
                "countryCode": "33",
                "platform": "smart_life"
            },
            "defaults": [
                {
                    "header": {
                        "code": "SUCCESS",
                        "payloadVersion": 1
                    },
                    "payload": {
                        "devices": [
                            {
                                "data": {
                                    "online": true,
                                    "state": 3,
                                    "support_stop": true
                                },
                                "dev_type": "cover",
                                "ha_type": "cover",
                                "icon": "https://images.tuyaus.com/smart/product_icon/cl.png",
                                "id": "XXXXXXXXXXXXXXXXXXX",
                                "name": "Window Cover for Front Door"
                            },
                            {
                                "data": {
                                    "online": true,
                                    "state": true
                                },
                                "dev_type": "switch",
                                "ha_type": "switch",
                                "icon": "https://images.tuyaus.com/smart/program_category_icon/kg.png",
                                "id": "XXXXXXXXXXXXXXXXXXX",
                                "name": "Bedroom Light"
                            }
                        ]
                    }
                }
            ],
            "scenes": []
        }


And the result of the log:
[2020-10-24 22:17:14] [TuyaWebPlatform] Initializing TuyaWebPlatform platform...
[2020-10-24 22:17:14] [TuyaWebPlatform] Finished initializing platform: TuyaWebPlatform
[2020-10-24 22:17:14] [TuyaWebPlatform] Loading accessory from cache: Smart socket
[2020-10-24 22:17:14] [TuyaWebPlatform] Requesting new token
[2020-10-24 22:17:14] [TuyaWebPlatform] Sending HTTP GET request to /homeassistant/skill - Header: {"name":"Discovery","namespace":"discovery","payloadVersion":1}.
[2020-10-24 22:17:14] [TuyaWebPlatform] Missing required `id` property on device type overwrite, received:
{
  "header": {
    "code": "SUCCESS",
    "payloadVersion": 1
  },
  "payload": {
    "devices": [
      {
        "data": {
          "online": true,
          "state": 3,
          "support_stop": true
        },
        "dev_type": "cover",
        "ha_type": "cover",
        "icon": "https://images.tuyaus.com/smart/product_icon/cl.png",
        "id": "38700750f4cfa20ad82d",
        "name": "Window Cover for Front Door"
      },
      {
        "data": {
          "online": true,
          "state": true
        },
        "dev_type": "switch",
        "ha_type": "switch",
        "icon": "https://images.tuyaus.com/smart/program_category_icon/kg.png",
        "id": "bf07d183d61df1cbd37hga",
        "name": "Bedroom Light"
      }
    ]
  }
}
[2020-10-24 22:17:14] [TuyaWebPlatform] Could not init class for device type [cover]
[2020-10-24 22:17:14] [TuyaWebPlatform] [Smart socket] deviceConfig: {
  data: { online: true, state: false },
  name: 'Smart socket',
  icon: 'https://images.tuyaeu.com/smart/icon/152956414744qw5qx565_0.jpg',
  id: 'bf07d183d61df1cbd37hga',
  dev_type: 'switch',
  ha_type: 'switch'
}

Can you help me to fix the config for cover device ?

**Comment by tbbruno** [comment]
I also would love cover support. I'm not very familiar with Python, but I'm available for testing and any help needed.
Here's the payload for my device:
```json
{
   "header":{
      "code":"SUCCESS",
      "payloadVersion":1
   },
   "payload":{
      "devices":[
         {
            "data":{
               "online":True,
               "state":2,
               "support_stop":True
            },
            "dev_type":"cover",
            "ha_type":"cover",
            "icon":"https://images.tuyaus.com/smart/program_category_icon/cl.png",
            "id":"31381150cc50e3ff03d0",
            "name":"Bedroom blinds"
         },
         {
            "data":{
               
            },
            "dev_type":"scene",
            "ha_type":"scene",
            "id":"WNW3SnShz6hOK6qC",
            "name":"If Schedule:6:05 PM ""Weekday,\\\"Bedroom blinds\\\" ""Control:Open"
         }
      ],
      "scenes":[
         
      ]
   }
}
```

For the time being, if some else is interested, I got it to partially work by changing the device type in the home-bridge config file to `switch`. Then it shows as "on" when the curtain is opened and "off" when the curtain is closed.
Far from ideal (specially with open curtain always showing as an "active" device in the home app), but does the job.

**Comment by milo526** [comment]
@josephpoon0506 please follow this issue for updates on cover support.

**Comment by josephpoon0506** [comment]
> @josephpoon0506 please follow this issue for updates on cover support.

thanks @milo526

**Comment by josephpoon0506** [comment]
Hi, this is the result from my device

Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {'online': True},
                                      'dev_type': 'cover',
                                      'ha_type': 'cover',
                                      'icon': 'https://images.tuyaus.com/smart/icon/ay1521165954459sVl6M/1592464776d5b3dbf1e85.png',
                                      'id': '855210025002915b8487',
                                      'name': '窗簾'},
                                  {   'data': {'online': True},
                                      'dev_type': 'cover',
                                      'ha_type': 'cover',
                                      'icon': 'https://images.tuyaus.com/smart/icon/ay1521165954459sVl6M/1592464776d5b3dbf1e85.png',
                                      'id': '855210025002915b6d67',
                                      'name': '細廳窗簾'},
                                  {   'data': {'online': True},
                                      'dev_type': 'cover',
                                      'ha_type': 'cover',
                                      'icon': 'https://images.tuyaus.com/smart/icon/ay1521165954459sVl6M/1592464776d5b3dbf1e85.png',
                                      'id': '855210025002915b6d70',
                                      'name': '大廳窗簾'},
                                  {   'data': {'online': True},
                                      'dev_type': 'cover',
                                      'ha_type': 'cover',
                                      'icon': 'https://images.tuyaus.com/smart/icon/ay1521165954459sVl6M/1592464776d5b3dbf1e85.png',
                                      'id': '855210025002915b6d8a',
                                      'name': '窗簾'},
                                  {   'data': {},
                                      'dev_type': 'scene',
                                      'ha_type': 'scene',
                                      'id': 'XC5rA4VAU6CA1XnC',
                                      'name': '廳窗簾升 星期六日'},
                                  {   'data': {},
                                      'dev_type': 'scene',
                                      'ha_type': 'scene',
                                      'id': 'q8sJBh8AT99Na51K',
                                      'name': '大廳窗簾落'},
                                  {   'data': {},
                                      'dev_type': 'scene',
                                      'ha_type': 'scene',
                                      'id': 'WaQgkwyKYIpC5TrR',
                                      'name': '大廳窗簾升'},
                                  {   'data': {},
                                      'dev_type': 'scene',
                                      'ha_type': 'scene',
                                      'id': 'D0xH5bGPe8V6zElN',
                                      'name': '細廳窗簾落'},
                                  {   'data': {},
                                      'dev_type': 'scene',
                                      'ha_type': 'scene',
                                      'id': 'XSg5EPA7Rp7IFe7u',
                                      'name': '細廳窗簾升'},
                                  {   'data': {},
                                      'dev_type': 'scene',
                                      'ha_type': 'scene',
                                      'id': 'RRKOYU5dkuSqqpGV',
                                      'name': 'Yobe房窗簾落'},
                                  {   'data': {},
                                      'dev_type': 'scene',
                                      'ha_type': 'scene',
                                      'id': 'L1VNS3LACoNOvZVo',
                                      'name': 'Yobe房窗簾升'},
                                  {   'data': {},
                                      'dev_type': 'scene',
                                      'ha_type': 'scene',
                                      'id': '479zCBd5U2A8sMpV',
                                      'name': '主人房窗簾升'},
                                  {   'data': {},
                                      'dev_type': 'scene',
                                      'ha_type': 'scene',
                                      'id': 'R6p9YEy4tOTtJGVH',
                                      'name': '主人房窗簾落'},
                                  {   'data': {},
                                      'dev_type': 'scene',
                                      'ha_type': 'scene',
                                      'id': 'qPfVkftnT8jcnbV5',
                                      'name': '全屋窗簾落'},
                                  {   'data': {},
                                      'dev_type': 'scene',
                                      'ha_type': 'scene',
                                      'id': 'gXhI73usRUBywJH0',
                                      'name': '全屋窗簾升'}],
                   'scenes': []}}

**Comment by ksxi2** [comment]
Hi all, sorry bit of a novice on GitHub so please mind my errors.

I've just purchased the Zemismart TM25TQ Roller Blind Motor (WiFi). 

I know that 'cover' devices are not supported but I would love to help where I can to get it supported.

Is there anything I can do?

**Comment by taaa22** [comment]
Dear @milo526 thank you for your effort to keep this plugin one of the best plugins in the homebridge.

Any update on supporting cover accessory?

**Comment by milo526** [comment]
Hey all;

pre-release version v0.5.4 might bring you a little Christmas gift 😉 

Could you please check It out and report if it works for you?

**Comment by ksxi2** [comment]
How does a n00b like me install this? I'm ready to test :)

**Comment by taaa22** [comment]
Dear @milo526,
Thank you for the Christmas gift 😉

I have 2 types of cover accessory,
Unfortunately, both are not shown.

**Comment by milo526** [comment]
> How does a n00b like me install this? I'm ready to test :)

Please see the [homebridge wiki on this topic](https://github.com/homebridge/homebridge/wiki/How-to-Install-Alternate-Plugin-Versions)

**Comment by milo526** [comment]
> Dear @milo526,
> Thank you for the Christmas gift 😉
> 
> I have 2 types of cover accessory,
> Unfortunately, both are not shown.

Thats too bad but I might need a little more information than this to help you 😛
Could you provide me with the log output after you rebooted the plugin.

**Comment by taaa22** [comment]
[12/20/2020, 20:53:22] [TuyaWebPlatform] Could not init class for device type [cover]

**Comment by taaa22** [comment]
`
{   'devices': [   {   'data': {   'online': True,
                                                  'state': 2,
                                                  'support_stop': True},
                                      'dev_type': 'cover',
                                      'ha_type': 'cover',
                                      'icon': 'https://images.tuyaeu.com/smart/program_category_icon/cl.png',
                                      'id': '31381150cc50e3ff0586',
                                      'name': 'Rolling Curtain'},
                                  {   'data': {   'online': True,
                                                  'state': 1,
                                                  'support_stop': True},
                                      'dev_type': 'cover',
                                      'ha_type': 'cover',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/1524640833egsjpb7nrnnczo9gn5xez5mi_0.png',
                                      'id': '71000544d8bfc0131655',
                                      'name': 'Main Curtain'} ] }
`

**Comment by ksxi2** [comment]
My motor isn't popping up, idk where to go from here

**Comment by ksxi2** [comment]
Okay, so I managed to get the motor to display on Homebridge (I changed the device_type to cover in the config).
I only have options to turn 'on' and 'off' but doing either doesn't do anything

**Comment by costispavlou** [comment]
> Hey all;
> 
> pre-release version v0.5.4 might bring you a little Christmas gift 😉
> 
> Could you please check It out and report if it works for you?

is the pre-release up yet? where can I test it?

**Comment by milo526** [comment]
Sorry for that; I might have slightly messed up my releases 😝 Will be fixed shortly!

**Comment by costispavlou** [comment]
awesome. let us know 👍

**Comment by taaa22** [comment]
Cannot wait for the best Christmas gift 😄

Thanks a bunch.

**Comment by sybrendotinga** [comment]
Same here. Installed v0.5.4. Result:
```
Could not init class for device type [cover]
```

**Comment by costispavlou** [comment]
> Same here. Installed v0.5.4. Result:
> 
> ```
> Could not init class for device type [cover]
> ```

how did you installed 0.5.4 ?

**Comment by milo526** [comment]
Version 0.6.0 is rolling out as we speak.

Please test that version instead of v0.5.4 😄

**Comment by taaa22** [comment]
It works like a charm 😍, for both types of my cover.

I noted that it doesn't support a percentage opening so it is either fully open or close.

**Comment by milo526** [comment]
> It works like a charm 😍, for both types of my cover.
> 
> I noted that it doesn't support a percentage opening so it is either fully open or close.

Great to hear!

Yeah currently it is only open or close.

Hopefully soon I will be able to add the "stop" option. that should enable you to stop it halfway through opening and/or closing.

Don't expect the ability to open a certain percentage to be available anytime soon, this is not supported by the API updating the plugin to support this will require a significant amount of time sadly.

**Comment by taaa22** [comment]
Thank you again.

With more testing I found that when you close the cover it gives you the correct status as it is showing in the first image.![image](https://user-images.githubusercontent.com/24491863/102723970-73c3e100-4325-11eb-8f36-e74026d7f7a0.png)

But after sometimes when I open the app again I found it like the following image ![image](https://user-images.githubusercontent.com/24491863/102724004-a66dd980-4325-11eb-8849-a68c608c7cf1.png)

**Comment by sybrendotinga** [comment]
> how did you installed 0.5.4 ?

If you ask this, you'd better not install an "alpha" release. This is pre-production stage. But, if you really "dare". Take a look at this:

> Please see the [homebridge wiki on this topic](https://github.com/homebridge/homebridge/wiki/How-to-Install-Alternate-Plugin-Versions)

**Comment by sybrendotinga** [comment]
> Don't expect the ability to open a certain percentage to be available anytime soon, this is not supported by the API updating the plugin to support this will require a significant amount of time sadly.

I was already afraid you'd say that. Looked at the code myself, and saw no real "quick" approach  in implementing it.

**Comment by milo526** [comment]
> > Don't expect the ability to open a certain percentage to be available anytime soon, this is not supported by the API updating the plugin to support this will require a significant amount of time sadly.
> 
> I was already afraid you'd say that. Looked at the code myself, and saw no real "quick" approach in implementing it.

Yeah what I suspect to be the best way would be - allow users to define how many seconds it takes to open or close. And based on the percentage (or difference in percentage) perform the open (or close) action for a certain amount of time.

Which is freaking ugly

**Comment by costispavlou** [comment]
i'll wait until you roll the update out, since i'm using hoobs.
also as regard the % open / close, yeah that'd be great. why would that be ugly? I mean, it's up to the user from there on.

**Comment by bwp91** [comment]
> > > Don't expect the ability to open a certain percentage to be available anytime soon, this is not supported by the API updating the plugin to support this will require a significant amount of time sadly.
> > 
> > 
> > I was already afraid you'd say that. Looked at the code myself, and saw no real "quick" approach in implementing it.
> 
> Yeah what I suspect to be the best way would be - allow users to define how many seconds it takes to open or close. And based on the percentage (or difference in percentage) perform the open (or close) action for a certain amount of time.
> 
> Which is freaking ugly

i have implemented this ugly method in my ewelink plugin. if you wanted some code 😅

**Comment by milo526** [comment]
> i'll wait until you roll the update out, since i'm using hoobs.
> also as regard the % open / close, yeah that'd be great. why would that be ugly? I mean, it's up to the user from there on.

Yeah it's up to the user from there on. 
This whole plugin is a giant mess 🙈.

And one way or another the questions always end up here 😛 and I am mostly the one to answer them and fix the issues.

The proposed solution is very wonky at best, I suspect that it will trigger a lot of errors, bugs, unhappy users.

I'd rather take the "Apple approach" of giving the users a little less flexibility but a better experience.

**Comment by costispavlou** [comment]
i get that, but you could add the implementation and let the user play with it a bit. i mean how bad can it be i.e. 0 (infinite) seconds up / 0 seconds down as default and can be edited in the plugins settings if needed. 

lastly when are you planning to roll the update? today? tomorrow ? no rush, just asking.

**Comment by josephpoon0506** [comment]
> > It works like a charm 😍, for both types of my cover.
> > I noted that it doesn't support a percentage opening so it is either fully open or close.
> 
> Great to hear!
> 
> Yeah currently it is only open or close.
> 
> Hopefully soon I will be able to add the "stop" option. that should enable you to stop it halfway through opening and/or closing.
> 
> Don't expect the ability to open a certain percentage to be available anytime soon, this is not supported by the API updating the plugin to support this will require a significant amount of time sadly.

@milo526, Thank you for your effort, but my curtain still not work. it show the below error message. it still not able to get the currect position status. Or 

[12/21/2020, 7:55:39 AM] [TuyaWebPlatform] [窗簾] - Unsetting debouncedDeviceStateRequestPromise
[12/21/2020, 7:55:39 AM] [TuyaWebPlatform] [窗簾] - Resolving resolveDeviceStateRequest from cache
[12/21/2020, 7:55:39 AM] [TuyaWebPlatform] [窗簾] Characteristic.CurrentPosition - [GET] undefined
[12/21/2020, 7:55:39 AM] [TuyaWebPlatform] [窗簾] Characteristic.CurrentPosition - Updating value { online: true }
[12/21/2020, 7:55:39 AM] [TuyaWebPlatform] [窗簾] Characteristic.CurrentPosition - Unexpected state value provided: undefined
[12/21/2020, 7:55:39 AM] [TuyaWebPlatform] [窗簾] Characteristic.TargetPosition - [GET] undefined
[12/21/2020, 7:55:39 AM] [TuyaWebPlatform] [窗簾] Characteristic.TargetPosition - Unexpected state value provided: undefined
[12/21/2020, 7:55:39 AM] [TuyaWebPlatform] [細窗簾] - Unsetting debouncedDeviceStateRequestPromise
[12/21/2020, 7:55:39 AM] [TuyaWebPlatform] [細窗簾] - Resolving resolveDeviceStateRequest from cache
[12/21/2020, 7:55:39 AM] [TuyaWebPlatform] [細窗簾] Characteristic.CurrentPosition - [GET] undefined
[12/21/2020, 7:55:39 AM] [TuyaWebPlatform] [細窗簾] Characteristic.CurrentPosition - Updating value { online: true }
[12/21/2020, 7:55:39 AM] [TuyaWebPlatform] [細窗簾] Characteristic.CurrentPosition - Unexpected state value provided: undefined
[12/21/2020, 7:55:39 AM] [TuyaWebPlatform] [細窗簾] Characteristic.TargetPosition - [GET] undefined
[12/21/2020, 7:55:39 AM] [TuyaWebPlatform] [細窗簾] Characteristic.TargetPosition - Unexpected state value provided: undefined
[12/21/2020, 7:55:39 AM] [TuyaWebPlatform] [大窗簾] - Unsetting debouncedDeviceStateRequestPromise
[12/21/2020, 7:55:39 AM] [TuyaWebPlatform] [大窗簾] - Resolving resolveDeviceStateRequest from cache
[12/21/2020, 7:55:39 AM] [TuyaWebPlatform] [大窗簾] Characteristic.TargetPosition - [GET] undefined
[12/21/2020, 7:55:39 AM] [TuyaWebPlatform] [大窗簾] Characteristic.TargetPosition - Unexpected state value provided: undefined
[12/21/2020, 7:55:39 AM] [TuyaWebPlatform] [大窗簾] Characteristic.CurrentPosition - [GET] undefined
[12/21/2020, 7:55:39 AM] [TuyaWebPlatform] [大窗簾] Characteristic.CurrentPosition - Updating value { online: true }
[12/21/2020, 7:55:39 AM] [TuyaWebPlatform] [大窗簾] Characteristic.CurrentPosition - Unexpected state value provided: undefined
[12/21/2020, 7:55:39 AM] [TuyaWebPlatform] [窗簾] - Unsetting debouncedDeviceStateRequestPromise
[12/21/2020, 7:55:39 AM] [TuyaWebPlatform] [窗簾] - Resolving resolveDeviceStateRequest from cache
[12/21/2020, 7:55:39 AM] [TuyaWebPlatform] [窗簾] Characteristic.TargetPosition - [GET] undefined
[12/21/2020, 7:55:39 AM] [TuyaWebPlatform] [窗簾] Characteristic.TargetPosition - Unexpected state value provided: undefined
[12/21/2020, 7:55:39 AM] [TuyaWebPlatform] [窗簾] Characteristic.CurrentPosition - [GET] undefined
[12/21/2020, 7:55:39 AM] [TuyaWebPlatform] [窗簾] Characteristic.CurrentPosition - Updating value { online: true }
[12/21/2020, 7:55:39 AM] [TuyaWebPlatform] [窗簾] Characteristic.CurrentPosition - Unexpected state value provided: undefined

**Comment by ksxi2** [comment]
Cover works on 0.6.3! Only have the option to open and close the cover. Would love to have the option to open the cover half way or something like that! Any possibility? The Tuya app has the option, I think the Home Assistant thing had the option, although idk if the API has it

**Comment by costispavlou** [comment]
@milo526 can you let me know when you're planning to update the plugin on hoobs? still shows the 0.4.8 as of today

**Comment by milo526** [comment]
> Cover works on 0.6.3! Only have the option to open and close the cover. Would love to have the option to open the cover half way or something like that! Any possibility? The Tuya app has the option, I think the Home Assistant thing had the option, although idk if the API has it

Please read the rest of this thread 😉 We already discussed that this is unlikely to happen soon.

@costispavlou there is no reason to ask this so often. Please remember that I am working on this alone, voluntarily, in my free time. But just so you know, it was just release, it will probably take a day to show up in hoobs.

**Comment by ksxi2** [comment]
> Please read the rest of this thread 😉 We already discussed that this is unlikely to happen soon.

My bad, thank you! I appreciate you working on this plugin!

**Comment by costispavlou** [comment]
@milo526 apologies if my comment sounded pushy. I was only wondering. I know and appreciate the effort you've put in this.

**Comment by sybrendotinga** [comment]
> Yeah what I suspect to be the best way would be - allow users to define how many seconds it takes to open or close. And based on the percentage (or difference in percentage) perform the open (or close) action for a certain amount of time.
> 
> Which is freaking ugly

I haven't really looked into the API (can't find any documentation), but I know that I had to update the 'schedule time', because my cover wasn't opening all the way. 

![image](https://user-images.githubusercontent.com/14016492/102903075-1f794800-4470-11eb-81fd-75cb6d2389d4.png)

Maybe you can use this value to determine how far 50% is? I don't think you can fetch the current percentage from the API, right?

**Comment by milo526** [comment]
I see that there is some unclarity here and that is partly on me for not being clear myself.

I will not add support for opening a window a certain percentage anytime soon.

This is mainly because it is very hard for me to actually test this since I do not own any of these Tuya-based window coverings.
This is partly because I have strong reason to suspect that this feature will be less than elegant at best and will trigger a lot of extra issues. I do not wish these upon me right now.

If somebody else wishes to work on this (@sybrendotinga ?) please feel welcome.
This would probably require changes to [`currentPosition.ts`](https://github.com/milo526/homebridge-tuya-web/blob/master/src/accessories/characteristics/currentPosition.ts) and to [`targetPosition.ts`](https://github.com/milo526/homebridge-tuya-web/blob/master/src/accessories/characteristics/targetPosition.ts).

The closest thing to "documentation" is the [PaulAnnekov/tuyaha](https://github.com/PaulAnnekov/tuyaha) repository. It has a python implementation for this API. It is also used by the Home Assistant integration. From there you should take a look at the [`cover.py`](https://github.com/PaulAnnekov/tuyaha/blob/master/tuyaha/devices/cover.py) class.

**Comment by sybrendotinga** [comment]
I tried to fork your repo this summer and tried to implement it myself, but I got stuck at the same things as you: bad documentation and I expected a lot of (external influenced) issues/side-effects based on the "time to open" solution.

**Comment by milo526** [comment]
￼there might be a way to get percentage based open and close to work since somebody might be willing to sponsor me a curtain device.

For the ones of you that see `support_stop: True` in their output above, could you please let me know the make and model (and preferably a direct link to where you purchased it)

This way I can hopefully buy such a device that has the required characteristics.

**Comment by sybrendotinga** [comment]
> ￼there might be a way to get percentage based open and close to work since somebody might be willing to sponsor me a curtain device.
> 
> For the ones of you that see `support_stop: True` in their output above, could you please let me know the make and model (and preferably a direct link to where you purchased it)
> 
> This way I can hopefully buy such a device that has the required characteristics.

How/where can I receive this information?

**Comment by milo526** [comment]
You can use [the steps under "How to check whether the api this library uses can control your device".](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device)

**Comment by sybrendotinga** [comment]
Thanks @milo526, hopefully this helps:

```
{
   "header":{
      "code":"SUCCESS",
      "payloadVersion":1
   },
   "payload":{
      "devices":[
         {
            "data":{
               "brightness":"255",
               "color_temp":5482,
               "online":True,
               "state":"false"
            },
            "dev_type":"light",
            "ha_type":"light",
            "icon":"https://images.tuyaeu.com/smart/icon/ay1541056239985fDGjj/15620320506d600f63b54.png",
            "id":"15680460c44f33a60b25",
            "name":"LED SMART Schutting"
         },
         {
            "data":{
               "brightness":"255",
               "color_temp":5482,
               "online":True,
               "state":"false"
            },
            "dev_type":"light",
            "ha_type":"light",
            "icon":"https://images.tuyaeu.com/smart/icon/ay1541056239985fDGjj/15620320506d600f63b54.png",
            "id":"15680460c44f33a5d2f8",
            "name":"LED SMART Poort"
         },
         {
            "data":{
               "online":True,
               "state":3,
               "support_stop":True
            },
            "dev_type":"cover",
            "ha_type":"cover",
            "icon":"https://images.tuyaeu.com/smart/icon/ay1509430484182dhmed/158372064901fba692f5f.png",
            "id":"bfb7e198ec8aa592e4xqyr",
            "name":"Zonnescherm"
         },
         {
            "data":{
               "brightness":"255",
               "color_temp":5482,
               "online":False,
               "state":"false"
            },
            "dev_type":"light",
            "ha_type":"light",
            "icon":"https://images.tuyaeu.com/smart/icon/ay1541056239985fDGjj/15620320506d600f63b54.png",
            "id":"15680460c44f33a7018e",
            "name":"LED SMART Achterin"
         }
      ],
      "scenes":[
         
      ]
   }
}
```

Maybe you can share your thoughts so we can discuss your solution.

**Comment by milo526** [comment]
So @sybrendotinga your device does support the stop functionality (The "Zonnescherm" device), could you post a link to the device that you use? So I can also buy it and ensure that I have a device with the proper functionality.

**Comment by sybrendotinga** [comment]
> So @sybrendotinga your device does support the stop functionality (The "Zonnescherm" device), could you post a link to the device that you use? So I can also buy it and ensure that I have a device with the proper functionality.

I would not recommend that ;-) It is to control my sunscreen ;-) 
https://nl.aliexpress.com/item/32963064005.html 

Maybe @Pelagious, @taaa22 or @Aekung can share theirs?

**Comment by milo526** [comment]
Stop functionality is now tracked in #145
Percentage based open is now tracked in #148 

If you are interested in either, please subscribe to the relevant issues.

For some users there is a bug in which the curtains are in a opening or closing state.
This is a bug and is tracked in #143

**Comment by taaa22** [comment]
> > So @sybrendotinga your device does support the stop functionality (The "Zonnescherm" device), could you post a link to the device that you use? So I can also buy it and ensure that I have a device with the proper functionality.
> 
> I would not recommend that ;-) It is to control my sunscreen ;-)
> https://nl.aliexpress.com/item/32963064005.html
> 
> Maybe @Pelagious, @taaa22 or @Aekung can share theirs?



[Smart Automatic Curtain Motor Track System](https://www.aliexpress.com/item/4000588299878.html?spm=a2g0s.9042311.0.0.1d444c4doyFERA)
[Smart Motorized Chain Roller Blinds](https://www.aliexpress.com/item/4001045079168.html?spm=a2g0o.productlist.0.0.79c73a5c3vILCv&algo_pvid=375f2c40-48d6-44e3-abaa-4ced94fd352e&algo_expid=375f2c40-48d6-44e3-abaa-4ced94fd352e-44&btsid=0bb0624516095271580226630e5413&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_)

**Comment by bSr43** [comment]
Hello,

Thank you for the plugin. I'm new to HomeBridge, so please forgive me if I've done anything wrong.
I have a bunch of [cover accessories from Konyks](https://www.amazon.fr/dp/B083BSZ7XV/ref=cm_sw_em_r_mt_dp_aDZ8FbJ3ZHZXY).

I've successfully installed HomeBridge and your plugin, the accessories have been discovered and they appear in HomeKit on my iDevices.

The problem I have is that the status shown in the Home application is not always correct.

In fact, after looking at the logs and the code (I'm not Typescript fluent, sorry about that…) it appears that the status of the accessories is updated by requesting their state from the cloud. The state can be either 1, 2 or 3 on this accessory. But if I understand the code of `targetPosition.ts` correctly, you assume that the state 1 means "opened", state 2 is "half opened" and state 3 is "closed". But from my experience, the state variable returned by the cloud server reflects the cover motor state, if it is currently active or not, and its direction; the states are 1 for "motor is active, and cover is opening", 2 for "motor is active, and cover is closing" and 3 for "motor is stopped". The state of the cover itself is not returned by the accessory, only the state of the motor is.

This is why, even if my covers are open, their states turn to "closed" after a few minutes, because the motor is stopped (state 3) and the plugin thinks that the cover is closed.

**Comment by milo526** [comment]
Thanks for that update @bSr43, this is exactly the issue with me not yet owning one of these devices 😛.
The previous api output suggested that the state was used to indicate if a window is opened or not.
Your explanation seems to fit in with the bug described in #143.
Could you confirm that the API output is identical on all accounts when your cover accessories are fully opened and fully closed.

**Comment by bSr43** [comment]
I have used the `debug_discovery.py` tool and the JSON looks like that:

```
{
    "header": {
        "code": "SUCCESS",
        "payloadVersion": 1
    },
    "payload": {
        "devices": [
            {
                "data": {
                    "online": true,
                    "state": 3,
                    "support_stop": true
                },
                "dev_type": "cover",
                "ha_type": "cover",
                "icon": "https://images.tuyaeu.com/smart/icon/ay1518345874298thrlS/157594986436cfb8dfee1.jpg",
                "id": "xxxxxxxxxxxxxxxxxxxx",
                "name": "Volet baie vitrée 1"
            },
            {
                "data": {
                    "online": true,
                    "state": 3,
                    "support_stop": true
                },
                "dev_type": "cover",
                "ha_type": "cover",
                "icon": "https://images.tuyaeu.com/smart/icon/ay1518345874298thrlS/157594986436cfb8dfee1.jpg",
                "id": "xxxxxxxxxxxxxxxxxxxx",
                "name": "Volet cellier"
            },
            {
                "data": {
                    "online": true,
                    "state": 3,
                    "support_stop": true
                },
                "dev_type": "cover",
                "ha_type": "cover",
                "icon": "https://images.tuyaeu.com/smart/icon/ay1518345874298thrlS/157594986436cfb8dfee1.jpg",
                "id": "xxxxxxxxxxxxxxxxxxxx",
                "name": "Volet salon 2"
            },
            {
                "data": {
                    "online": true,
                    "state": 3,
                    "support_stop": true
                },
                "dev_type": "cover",
                "ha_type": "cover",
                "icon": "https://images.tuyaeu.com/smart/icon/ay1518345874298thrlS/157594986436cfb8dfee1.jpg",
                "id": "xxxxxxxxxxxxxxxxxxxx",
                "name": "Volet cuisine"
            },
            {
                "data": {
                    "online": true,
                    "state": 3,
                    "support_stop": true
                },
                "dev_type": "cover",
                "ha_type": "cover",
                "icon": "https://images.tuyaeu.com/smart/icon/ay1518345874298thrlS/157594986436cfb8dfee1.jpg",
                "id": "xxxxxxxxxxxxxxxxxxxx",
                "name": "Volet salon 1"
            },
            {
                "data": {
                    "online": true,
                    "state": 3,
                    "support_stop": true
                },
                "dev_type": "cover",
                "ha_type": "cover",
                "icon": "https://images.tuyaeu.com/smart/icon/ay1518345874298thrlS/157594986436cfb8dfee1.jpg",
                "id": "xxxxxxxxxxxxxxxxxxxx",
                "name": "Volet baie vitrée 2"
            },
            {
                "data": {
                    "online": true,
                    "state": 3,
                    "support_stop": true
                },
                "dev_type": "cover",
                "ha_type": "cover",
                "icon": "https://images.tuyaeu.com/smart/icon/ay1518345874298thrlS/157594986436cfb8dfee1.jpg",
                "id": "xxxxxxxxxxxxxxxxxxxx",
                "name": "Volet bureau"
            }
        ],
        "scenes": []
    }
}
```

When I have generated the JSON, some covers were opened, others were closed. But every cover has the state "3" because the motor was not running. When I start the motor by using the physical switch, the state is updated accordingly to my previous explanation, ie when the cover is opening (until the motor stops), the state is "1", and when the cover is closing, the state is "2". As soon as I hear the click which indicated that the cover switch has finished its work, the state is "3".

I really appreciate the time you are spending on this project, and cannot even imagine how hard it could be to write support for something you don't even own! Thank you for that!

**Comment by milo526** [comment]
I just release a pre-release with some improvements for cover devices.
You can now also overwrite your window covering to a window.
This will enable some extra security features (I believe your phone needs to be unlocked in order to open a window), it will give you notifications on open/close and it gives you some shiny new icons.

How to install a pre-release version.
Logically do this for the @milo526/homebridge-tuya-web or TuyaWebPlatform plugin.
You should be able to install version v0.8.0-0.
Please let me know how that works for you!

**Comment by taaa22** [comment]
> I just release a pre-release with some improvements for cover devices.
> 
> You can now also overwrite your window covering to a window.
> 
> This will enable some extra security features (I believe your phone needs to be unlocked in order to open a window), it will give you notifications on open/close and it gives you some shiny new icons.
> 
> 
> 
> [How to install a pre-release version.](https://github.com/homebridge/homebridge/wiki/How-to-Install-Alternate-Plugin-Versions)
> 
> Logically do this for the @milo526/homebridge-tuya-web or TuyaWebPlatform plugin.
> 
> You should be able to install version v0.8.0-0.
> 
> Please let me know how that works for you!

Thank you for this update.

- Hold position for covers(Not working)
- Allow overwriting devices to Window type (Working with the same reporting cover state issue)
- Wrongly reported cover state (Still not fixed)

**Comment by milo526** [comment]
@taaa22 please see my response in #145 with regards to the stop option.
In short, the Home.app has no support for this functionality, third party apps might. I have confirmed it working using the Eve app.
